@extends('layouts.app')
@section('title','Manajemen User')
@section('content')
<div class="card"><div class="card-body p-0">
 <div class="d-flex flex-wrap gap-3 justify-content-between align-items-center p-4 border-bottom">
  <div><div class="section-card-title">Daftar User</div><small class="text-secondary">Kelola akun, admin tambahan, dan reset password.</small></div>
  <div class="d-flex gap-2"><form class="d-flex gap-2"><input class="form-control" name="q" value="{{request('q')}}" placeholder="Cari nama atau email"><button class="btn btn-outline-secondary"><i class="fa-solid fa-magnifying-glass"></i></button></form><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createUser"><i class="fa-solid fa-user-plus me-2"></i>Tambah User</button></div>
 </div>
 <div class="table-responsive"><table class="table align-middle"><thead><tr><th>User</th><th>Role</th><th>Telepon</th><th>Status</th><th>Login Terakhir</th><th class="text-end">Aksi</th></tr></thead><tbody>
 @forelse($users as $user)
 <tr><td><span class="table-title">{{$user->name}}</span><small class="d-block text-secondary">{{$user->email}}</small></td><td><span class="badge badge-soft">{{$user->role}}</span></td><td>{{$user->phone?:'-'}}</td><td><span class="badge rounded-pill {{$user->is_active?'text-bg-success':'text-bg-secondary'}}">{{$user->is_active?'Aktif':'Nonaktif'}}</span></td><td>{{$user->last_login_at?->format('d/m/Y H:i')??'-'}}</td><td class="text-end"><button class="icon-button" title="Ubah / Reset Password" data-bs-toggle="modal" data-bs-target="#editUser{{$user->id}}"><i class="fa-regular fa-pen-to-square"></i></button>@if($user->role!=='Super Admin' && !auth()->user()->is($user))<form class="d-inline" method="post" action="{{route('users.destroy',$user)}}" data-confirm-action data-confirm-tone="danger" data-confirm-title="Hapus akun" data-confirm-message="Akun ini akan dihapus dan tidak dapat digunakan lagi.">@csrf @method('delete')<button class="icon-button text-danger" title="Hapus akun"><i class="fa-regular fa-trash-can"></i></button></form>@endif</td></tr>
 @empty<tr><td colspan="6" class="text-center py-5 text-secondary">Belum ada user.</td></tr>@endforelse
 </tbody></table></div><div class="p-4">{{$users->links()}}</div>
</div></div>

<div class="modal fade" id="createUser" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0" style="border-radius:16px"><form method="post" action="{{route('users.store')}}">@csrf<input type="hidden" name="_user_form" value="create"><div class="modal-header border-0 px-4 pt-4"><h5 class="modal-title fw-bold">Tambah User</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body px-4"><div class="row g-3">
 <div class="col-12"><label class="form-label">Nama *</label><input class="form-control" name="name" value="{{old('_user_form')==='create'?old('name'):''}}" required></div>
 <div class="col-12"><label class="form-label">Email *</label><input class="form-control" type="email" name="email" value="{{old('_user_form')==='create'?old('email'):''}}" required></div>
 <div class="col-md-6"><label class="form-label">Telepon</label><input class="form-control" name="phone" value="{{old('_user_form')==='create'?old('phone'):''}}"></div><div class="col-md-6"><label class="form-label">Role *</label><select class="form-select" name="role" required><option>Admin</option>@if(auth()->user()->hasRole('Super Admin'))<option>Super Admin</option>@endif</select></div>
 <div class="col-md-6"><label class="form-label">Password *</label><input class="form-control" type="password" name="password" minlength="8" required></div><div class="col-md-6"><label class="form-label">Konfirmasi Password *</label><input class="form-control" type="password" name="password_confirmation" minlength="8" required></div>
 </div></div><div class="modal-footer border-0 px-4 pb-4"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan User</button></div></form></div></div></div>

@foreach($users as $user)
@php($oldUser = (string)old('_user_form') === (string)$user->id)
<div class="modal fade" id="editUser{{$user->id}}" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0" style="border-radius:16px"><form method="post" action="{{route('users.update',$user)}}">@csrf @method('put')<input type="hidden" name="_user_form" value="{{$user->id}}"><div class="modal-header border-0 px-4 pt-4"><div><h5 class="modal-title fw-bold">Update User</h5><small class="text-secondary">Kosongkan password jika tidak ingin menggantinya.</small></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body px-4"><div class="row g-3">
 <div class="col-12"><label class="form-label">Nama *</label><input class="form-control" name="name" value="{{$oldUser?old('name'):$user->name}}" required></div><div class="col-12"><label class="form-label">Email *</label><input class="form-control" type="email" name="email" value="{{$oldUser?old('email'):$user->email}}" required></div>
 <div class="col-md-6"><label class="form-label">Telepon</label><input class="form-control" name="phone" value="{{$oldUser?old('phone'):$user->phone}}"></div><div class="col-md-6"><label class="form-label">Role *</label><select class="form-select" name="role" @disabled(auth()->user()->is($user) || !auth()->user()->hasRole('Super Admin'))>@foreach(['Admin','Super Admin'] as $role)<option @selected(($oldUser?old('role'):$user->role)===$role)>{{$role}}</option>@endforeach</select>@if(auth()->user()->is($user) || !auth()->user()->hasRole('Super Admin'))<input type="hidden" name="role" value="{{$user->role}}">@endif</div>
 <div class="col-md-6"><label class="form-label">Status *</label><select class="form-select" name="is_active" @disabled(auth()->user()->is($user) || !auth()->user()->hasRole('Super Admin'))><option value="1" @selected(($oldUser?old('is_active'):$user->is_active)==1)>Aktif</option><option value="0" @selected(($oldUser?old('is_active'):$user->is_active)==0)>Nonaktif</option></select>@if(auth()->user()->is($user) || !auth()->user()->hasRole('Super Admin'))<input type="hidden" name="is_active" value="{{$user->is_active?1:0}}"><small class="text-secondary">Hanya Super Admin yang dapat mengubah status.</small>@endif</div>
 <div class="col-md-6"><label class="form-label">Password Baru</label><input class="form-control" type="password" name="password" minlength="8"></div><div class="col-md-6 ms-auto"><label class="form-label">Konfirmasi Password</label><input class="form-control" type="password" name="password_confirmation" minlength="8"></div>
 </div></div><div class="modal-footer border-0 px-4 pb-4"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div></div>
@endforeach
@push('scripts')<script>document.addEventListener('DOMContentLoaded',function(){@if($errors->any() && old('_user_form'))bootstrap.Modal.getOrCreateInstance(document.getElementById('{{old('_user_form')==='create'?'createUser':'editUser'.old('_user_form')}}')).show();@endif});</script>@endpush
@endsection
