@extends('layouts.app')
@section('title','Master '.$title)
@section('content')
<div class="card"><div class="card-body p-0"><div class="d-flex flex-wrap gap-3 justify-content-between align-items-center p-4 border-bottom"><div><div class="section-card-title">Daftar {{$title}}</div><small class="text-secondary">Kelola dan lihat informasi {{$title}} secara lengkap.</small></div><div class="d-flex flex-wrap gap-2"><form class="d-flex gap-2"><input class="form-control" name="q" value="{{request('q')}}" placeholder="Cari {{$title}}..."><button class="btn btn-outline-secondary"><i class="fa-solid fa-magnifying-glass"></i></button></form><a class="btn btn-primary d-flex align-items-center" href="{{route($resource.'.create')}}"><i class="fa-solid fa-plus me-2"></i>Tambah {{$title}}</a></div></div>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Nama</th>@if($resource==='products')<th>Kode / SKU</th><th>Gudang</th><th>Stok</th>@elseif($resource==='suppliers')<th>PIC</th><th>Telepon</th>@elseif($resource==='salespeople')<th>Cabang</th><th>Status</th>@else<th>PIC</th><th>Alamat</th>@endif<th class="text-end">Aksi</th></tr></thead><tbody>
@forelse($rows as $row)<tr><td><a class="table-title" href="{{route($resource.'.show',$row)}}">{{$row->name}}</a><small class="d-block text-secondary">#{{str_pad($row->id,4,'0',STR_PAD_LEFT)}}</small></td>@if($resource==='products')<td>{{$row->code}}<small class="d-block text-secondary">{{$row->sku}}</small></td><td>{{$row->warehouse?->name??'-'}}</td><td><span class="badge rounded-pill {{$row->current_stock<=$row->minimum_stock?'text-bg-danger':'badge-soft'}}">{{$row->current_stock}} {{$row->unit}}</span></td>@elseif($resource==='suppliers')<td>{{$row->pic??'-'}}</td><td>{{$row->phone??'-'}}</td>@elseif($resource==='salespeople')<td>{{$row->branch??'-'}}</td><td><span class="badge rounded-pill {{$row->status==='active'?'badge-soft':'text-bg-secondary'}}">{{ucfirst($row->status)}}</span></td>@else<td>{{$row->pic??'-'}}</td><td class="text-truncate" style="max-width:260px">{{$row->address??'-'}}</td>@endif<td class="text-end text-nowrap"><a class="icon-button" title="Lihat detail" href="{{route($resource.'.show',$row)}}"><i class="fa-regular fa-eye"></i></a> <a class="icon-button" title="Ubah" href="{{route($resource.'.edit',$row)}}"><i class="fa-regular fa-pen-to-square"></i></a> <form class="d-inline" method="post" data-confirm-action data-confirm-tone="danger" data-confirm-title="Arsipkan data" data-confirm-message="Data ini akan diarsipkan dan tidak dihitung sebagai data aktif." action="{{route($resource.'.destroy',$row)}}">@csrf @method('delete')<button class="icon-button text-danger" title="Arsipkan"><i class="fa-regular fa-trash-can"></i></button></form></td></tr>
@empty<tr><td colspan="6" class="text-center py-5 text-secondary"><i class="fa-regular fa-folder-open fs-3 d-block mb-2"></i>Belum ada data.</td></tr>@endforelse
</tbody></table></div><div class="p-4">{{$rows->links()}}</div></div></div>
@endsection
