@extends('layouts.app')
@section('title',$type==='inventory-history'?'Riwayat Persediaan Harian':'Laporan '.ucfirst($type))
@section('content')
<div class="card"><div class="card-body p-0"><div class="d-flex flex-wrap gap-3 justify-content-between align-items-center p-4 border-bottom"><div><div class="section-card-title">{{$type==='inventory-history'?'Riwayat Total Persediaan Harian':'Data Laporan'}}</div><small class="text-secondary">{{$type==='inventory-history'?'Rekap stok dan nilai persediaan pada akhir setiap hari.':'Ringkasan data operasional StockFlow'}}</small></div><div class="d-flex flex-wrap gap-2"><div class="btn-group"><a class="btn btn-outline-primary btn-sm {{$type==='inventory'?'active':''}}" href="{{route('reports','inventory')}}">Persediaan</a><a class="btn btn-outline-primary btn-sm {{$type==='inventory-history'?'active':''}}" href="{{route('reports','inventory-history')}}">Riwayat Harian</a><a class="btn btn-outline-primary btn-sm {{$type==='inbound'?'active':''}}" href="{{route('reports','inbound')}}">Barang Masuk</a><a class="btn btn-outline-primary btn-sm {{$type==='outbound'?'active':''}}" href="{{route('reports','outbound')}}">Barang Keluar</a></div><button onclick="window.print()" class="btn btn-dark btn-sm"><i class="fa-solid fa-print me-1"></i>Cetak</button></div></div>
<div class="table-responsive"><table class="table align-middle"><thead><tr>@if($type==='inventory')<th>Kode</th><th>Barang</th><th>Supplier</th><th>Gudang</th><th>Stok</th><th>Nilai Persediaan</th><th></th>@elseif($type==='inventory-history')<th>Tanggal</th><th>Total Unit</th><th>Barang Masuk</th><th>Barang Keluar</th><th>Total Nilai Persediaan</th>@else<th>Tanggal</th><th>Referensi</th><th>Partner</th><th>Barang</th><th>Qty</th><th></th>@endif</tr></thead><tbody>
@if($type!=='inventory-history' && $rows->isEmpty())<tr><td colspan="7" class="text-center text-secondary py-5"><i class="fa-regular fa-folder-open fs-3 d-block mb-2"></i>Tidak ada data untuk laporan ini.</td></tr>
@elseif($type==='inventory')@foreach($rows as $r)<tr><td>{{$r->code}}</td><td><a class="table-title" href="{{route('products.show',$r)}}">{{$r->name}}</a></td><td>{{$r->supplier?->name??'-'}}</td><td>{{$r->warehouse?->name??'-'}}</td><td><span class="badge rounded-pill badge-soft">{{$r->current_stock}} {{$r->unit}}</span></td><td>Rp {{number_format($r->current_stock*$r->cost_price,0,',','.')}}</td><td><a class="icon-button" title="Lihat detail" href="{{route('products.show',$r)}}"><i class="fa-regular fa-eye"></i></a></td></tr>@endforeach
@elseif($type==='inventory-history')@foreach($rows as $r)<tr><td class="fw-semibold">{{$r['date']->translatedFormat('d F Y')}}</td><td>{{$r['units']}} unit</td><td class="text-success fw-semibold">+{{$r['inbound']}}</td><td class="text-danger fw-semibold">-{{$r['outbound']}}</td><td class="fw-bold">Rp {{number_format($r['value'],0,',','.')}}</td></tr>@endforeach
@else @foreach($rows as $r) @foreach($r->items as $i)<tr><td>{{$r->transaction_date->format('d M Y')}}</td><td>{{$r->reference_no??'-'}}</td><td>{{$r->supplier?->name??$r->salesperson?->name??'-'}}</td><td>@if($i->product && !$i->product->trashed())<a class="table-title" href="{{route('products.show',$i->product)}}">{{$i->product->name}}</a>@else<span class="fw-semibold">{{$i->product?->name??'Produk tidak tersedia'}}</span> <span class="badge text-bg-secondary">Diarsipkan</span>@endif</td><td>{{$i->qty}}</td><td>@if($i->product && !$i->product->trashed())<a class="icon-button" title="Lihat barang" href="{{route('products.show',$i->product)}}"><i class="fa-regular fa-eye"></i></a>@else—@endif</td></tr>@endforeach @endforeach
@endif
</tbody></table></div></div></div>
@endsection
