<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::table('users', function(Blueprint $t){$t->string('role')->default('Sales');$t->string('phone')->nullable();$t->boolean('is_active')->default(true);$t->timestamp('last_login_at')->nullable();});
 Schema::create('warehouses',function(Blueprint $t){$t->id();$t->string('name');$t->text('address')->nullable();$t->string('pic')->nullable();$t->softDeletes();$t->timestamps();});
 Schema::create('suppliers',function(Blueprint $t){$t->id();$t->string('name');$t->string('pic')->nullable();$t->string('email')->nullable();$t->string('phone')->nullable();$t->text('address')->nullable();$t->string('city')->nullable();$t->string('npwp')->nullable();$t->text('notes')->nullable();$t->softDeletes();$t->timestamps();});
 Schema::create('salespeople',function(Blueprint $t){$t->id();$t->string('name');$t->string('branch')->nullable();$t->string('area')->nullable();$t->string('email')->nullable();$t->string('phone')->nullable();$t->string('status')->default('active');$t->softDeletes();$t->timestamps();});
 Schema::create('products',function(Blueprint $t){$t->id();$t->string('photo')->nullable();$t->string('barcode')->unique();$t->string('qr_code')->nullable();$t->string('code')->unique();$t->string('sku')->unique();$t->string('name');$t->string('category')->nullable();$t->string('brand')->nullable();$t->foreignId('supplier_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('warehouse_id')->constrained();$t->string('rack_location')->nullable();$t->string('unit')->default('Pcs');$t->decimal('cost_price',15,2)->default(0);$t->decimal('selling_price',15,2)->default(0);$t->integer('minimum_stock')->default(0);$t->integer('current_stock')->default(0);$t->string('status')->default('active');$t->text('notes')->nullable();$t->softDeletes();$t->timestamps();});
 Schema::create('stock_transactions',function(Blueprint $t){$t->id();$t->date('transaction_date');$t->string('type');$t->string('reference_no')->nullable();$t->foreignId('supplier_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('salesperson_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('warehouse_id')->nullable()->constrained()->nullOnDelete();$t->string('destination')->nullable();$t->decimal('discount',15,2)->default(0);$t->decimal('tax',15,2)->default(0);$t->string('attachment')->nullable();$t->text('notes')->nullable();$t->foreignId('user_id')->constrained();$t->timestamps();});
 Schema::create('stock_transaction_items',function(Blueprint $t){$t->id();$t->foreignId('stock_transaction_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained();$t->integer('qty');$t->decimal('price',15,2)->default(0);$t->timestamps();});
 Schema::create('stock_histories',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->dateTime('occurred_at');$t->integer('quantity_in')->default(0);$t->integer('quantity_out')->default(0);$t->integer('balance');$t->string('activity');$t->morphs('reference');$t->timestamps();});
 Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('event');$t->string('subject_type')->nullable();$t->unsignedBigInteger('subject_id')->nullable();$t->string('ip_address')->nullable();$t->json('properties')->nullable();$t->timestamps();});
} public function down():void {Schema::dropIfExists('audit_logs');Schema::dropIfExists('stock_histories');Schema::dropIfExists('stock_transaction_items');Schema::dropIfExists('stock_transactions');Schema::dropIfExists('products');Schema::dropIfExists('salespeople');Schema::dropIfExists('suppliers');Schema::dropIfExists('warehouses');Schema::table('users',fn(Blueprint $t)=>$t->dropColumn(['role','phone','is_active','last_login_at']));}};
